using System;
using DevExpress.XtraCharts;

namespace ChartBindingWithPanes {
    public partial class MainForm : DevExpress.XtraEditors.XtraForm {
        public MainForm() {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            gspTableAdapter.Fill(gspDataSet.GSP);
        }

        private void OnFormLoad(object sender, EventArgs e) {
            chartControl.BoundDataChanged += OnChartBoundDataChanged;
        }
        private void OnChartBoundDataChanged(object sender, EventArgs e) {
            ChartControl chart = (ChartControl)sender;
            if(chart.Series.Count > 0) {
                XYDiagram diagram = (XYDiagram)chart.Diagram;
                diagram.Panes.Clear();
                for(int i = 1; i < chart.Series.Count; i++) {
                    XYDiagramPane pane = new XYDiagramPane(String.Format(@"Pane {0}", i));
                    diagram.Panes.Add(pane);
                    XYDiagramSeriesViewBase view = (XYDiagramSeriesViewBase)chart.Series[i].View;
                    view.Pane = pane;
                }
            }
        }
    }
}