Imports System
Imports DevExpress.XtraCharts

Namespace ChartBindingWithPanes
	Partial Public Class MainForm
		Inherits DevExpress.XtraEditors.XtraForm

		Public Sub New()
			InitializeComponent()
			' This line of code is generated by Data Source Configuration Wizard
			gspTableAdapter.Fill(gspDataSet.GSP)
		End Sub

		Private Sub OnFormLoad(ByVal sender As Object, ByVal e As EventArgs) Handles Me.Load
			AddHandler chartControl.BoundDataChanged, AddressOf OnChartBoundDataChanged
		End Sub
		Private Sub OnChartBoundDataChanged(ByVal sender As Object, ByVal e As EventArgs)
			Dim chart As ChartControl = DirectCast(sender, ChartControl)
			If chart.Series.Count > 0 Then
				Dim diagram As XYDiagram = CType(chart.Diagram, XYDiagram)
				diagram.Panes.Clear()
				For i As Integer = 1 To chart.Series.Count - 1
					Dim pane As New XYDiagramPane(String.Format("Pane {0}", i))
					diagram.Panes.Add(pane)
					Dim view As XYDiagramSeriesViewBase = CType(chart.Series(i).View, XYDiagramSeriesViewBase)
					view.Pane = pane
				Next i
			End If
		End Sub
	End Class
End Namespace